### ISSUE TITLE
Issues related to the use of qgis2web with qgis 3.8 Zanzibar

### ISSUE THREAD

**Issue by blowsuffercartography** [qgis2web/qgis2web#775] opened 2019-07-19 10:18 UTC
info qgis:

QGIS version : 3.8.0-Zanzibar
QGIS code revision: 11aff65f10
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against: GDAL/OGR2.4.1
Running against: GDAL/OGR: 2.4.1
Compiled against GEOS: 3.7.2-CAPI-1.11.0
Running against GEOS: 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version: 9.2.4
SpatiaLite Version: 4.3.0
QWT Version: 6.1.3
QScintilla2 Version: 2.10.8
Compiled against PROJ: 5.2.0
Running against PROJ: Rel. 5.2.0, September 15th, 2018
OS Version: Windows 10 (10.0)

info qgis2web : version 3.7.0

Problem: Generating a webgis with qgis 3.8 and qgis2web, within which the new functionality of qgis 3.8 html widgets is used,  point .shp file are correctly visualized while polygon .shp files are not visualized by the html widget. Anyone knows the problem?

**Comment by tomchadwin** [comment] 2019-07-19 10:30
We need a few more details. Exactly what did you do, and exactly how did it fail? If you can upload your project and layer files, we can then recreate the issue to investigate.

**Comment by blowsuffercartography** [comment] 2019-07-19 10:34
Of course now I prepare an example project

**Comment by blowsuffercartography** [comment] 2019-07-19 11:02
[qgis2servertest.zip](https://github.com/tomchadwin/qgis2web/files/3410766/qgis2servertest.zip)
[qgistestproject.zip](https://github.com/tomchadwin/qgis2web/files/3410767/qgistestproject.zip)

In this test the script generated by the html widget (as seen in the qgis project), is not displayed on the points nor on the areas, in the qgis2web project.

**Comment by riccardoklinger** [comment] 2019-07-21 19:58
furthermore qgis3.8 does uses a different qt version that has some changes like the use of QWebInspector in maindialog.py which leads to failed tests.

**Comment by mbutterz** [comment] 2019-07-23 11:17
Hi Tom,

I'm unable to generate a qgis2web map using Zanzibar 3.8.0 (EPSG:3857)

OpenLayers - shows the zoom scale and layers panel, but no map.

Leaflet - shows nothing and crashes with the following Python error:
![2](https://user-images.githubusercontent.com/47577758/61708062-c7eb2000-ad43-11e9-854f-7113af28607f.JPG)

**Comment by riccardoklinger** [comment] 2019-07-23 12:07
Could you paste  the full  output  please?

**Comment by mbutterz** [comment] 2019-07-23 12:44
![5](https://user-images.githubusercontent.com/47577758/61713232-f7a02500-ad4f-11e9-968e-90bf15cc1383.JPG)

**Comment by tomchadwin** [comment] 2019-07-23 12:48
@mbutterz You issue looks like that in https://github.com/tomchadwin/qgis2web/issues/705. The fixes for that have been committed to master, but have not yet been released in a qgis2web version. Please have a look at that issue and see if any of the causes listed there apply to you (no symbols, point displacement, etc).

**Closed** 2024-01-02 04:33 UTC
