### ISSUE TITLE
Export Using Time Layers Error

### ISSUE THREAD

**Issue by mistyblue17** [qgis2web/qgis2web#550] opened 2017-10-02 04:58 UTC
Hello!
I get the follow error when trying to export my map from QGIS to Leaflet. I have 6 layers with time properties that I want to export. I'm wondering if this error has to do with that. I only have one column with date values in YYYY-MM format. So for "Time from" I select "FIELD:date" and for "Time to" I select "FIELD:date". Even if I leave "Time to" empty, or if I only try to do 1 layer with time, I still get the error below. I'm using QGIS 2.8.13 and the most fecent version of qgis2Web (2.28.0).
Here is the link to the CSV file upon which one of the time layers is built. 
https://1drv.ms/u/s!Agk5bfVj73y9lYtKveK_5N4dJxOp5Q

2017-10-01T23:41:27	1	Traceback (most recent call last):
			  File "C:/Users/misty/.qgis2/python/plugins\qgis2web\ui_timedialog.py", line 283, in saveMap
			    self.saveLeafletMap()
			  File "C:/Users/misty/.qgis2/python/plugins\qgis2web\ui_timedialog.py", line 289, in saveLeafletMap
			    root, dirs, files = os.walk(dir).next()
			StopIteration

**Comment by tomchadwin** [comment] 2017-10-02 10:17
Can you help, @ruz76?

**Comment by ruz76** [comment] 2017-10-04 19:02
I am sorry, but I know about that problem. The extension now works only with string or integer fields. So you have to convert your fields from 2017-02-28 to something like 20170228. I have planned to add conversion for date type, but did not done yet.

**Comment by ruz76** [comment] 2017-10-04 19:03
And there is not supported time stamp, but only time span now. So you need two fields as well.

**Comment by ruz76** [comment] 2017-10-05 17:21
I am sorry. My reply was not exact. The error you have is probably caused that there is not properly set output directory. Please try to export project without time, save project and then add time. But what I have written about date and time stamp is correct. They are not implemented.

**Comment by ruz76** [comment] 2017-10-05 17:26
I am sorry again. I have tested the date field in format YYYY-MM-DD and it works as well. Now I am looking at time stamp, how to simply add this possibility to the code. From user point of view it could be confusing to use the same dialog, but maybe not, if I add some information to it. Something like: If you select only time from field it will act as time stamp.

**Comment by ruz76** [comment] 2017-10-05 17:32
I have tested your data and now I see another problem, but I have to do some changes to the code.

**Comment by ruz76** [comment] 2017-10-05 18:02
So the extension now works correctly only for year data. I have tried to simply convert your data to required format. It works, but the time axis has a problem that makes output not usable from user point of view. SO I have to think more about it and add solution for month and day data as well, maybe time as well.

**Comment by mistyblue17** [comment] 2017-10-05 19:09
I can work with year only for now. Also I don't think it would be too
confusing to have a date field for the time series and a separate field for
time stamp. Perhaps this would help the improve the display of the time
slider on the user side in Leaflet. Please let me know how I can help you
troubleshoot or develop a solution. I'm still a bit new to coding, but I'll
do my best.

**Comment by tomchadwin** [comment] 2017-10-05 20:41
Thanks for all this work, @ruz76. I've not had a chance to understand your code yet, so I'm sorry I'm not much help with this issue.

**Comment by ruz76** [comment] 2017-10-06 18:35
I have created sample output from your Syracuse data and I will change the functionality in the plugin as soon as possible. The example is available at https://github.com/ruz76/qgis2web_time_extension/blob/master/qgis2web_2017_10_05-19_45_21_587083.zip

**Comment by tomchadwin** [comment] 2017-11-25 11:11
Is this working any better now that I've merged in @ruz76's latest version (thanks!).

**Comment by philippgaertner** [comment] 2017-12-07 08:53
Hi there, I added the time information after the initial export and it works now. Unfortunately the slider is behind the background map and only visible when the map is refreshing. 
How may I move the slider on top of the map?

By the way, this is a great plugin!!!

**Comment by ruz76** [comment] 2017-12-07 09:15
I think that the way is to add the slider as a map control. I will try some tests.

**Comment by klrblz** [comment] 2018-02-20 15:57
Hi,

I try to use qgis2web 2.33.1 with two YYYYMMDD fields but it looks like it works only with year...

My data: (test data for example)
ID START STOP
1 20180301 20180501
2 20180501 20180201
3 20180301 20190501

If i put the first cursor in 2018 and second cursor in 2019, i can see all objects
if i put the two cursors in 2019, i can see the third object only
If i put the two cursors in 2018, everything disappear => Why ?

My goal is to work only with MMDD dates (or YYYYMMDD dates but always for the same year) Is it possible?


Sorry for my awful english and thanks for your help !


Claire

**Comment by HerbFargus** [comment] 2018-03-02 05:50
I've been playing with this a bit as well with QGIS 3.0 but it seems that it's only recognising the openlayers tilemap rather than my shapefile. I don't want to hijack this thread so let me know if I should open a separate ticket for this, but I'm happy to provide logs/ testing/ etc. as I'm also very interested in this feature.

**Comment by ruz76** [comment] 2018-03-02 07:23
I did not test it for QGIS 3 yet, but it should work with QGIS 2. The new version should be quite OK, but there can be problem with slider visibility. Could you please place somewhere sample of your data. I can try plugin with them to check, if there is not any other bug.

**Comment by HerbFargus** [comment] 2018-03-02 07:27
I'm using this dataset:

http://publications.newberry.org/ahcbp/downloads/gis/OR_AtlasHCB.zip

I can provide a smaller subset of the data if that's easier?

It has a start and end date field with a date data type (mm/dd/yyyy) and a string data type (yyyymmdd)

**Comment by klrblz** [comment] 2018-03-02 08:58
[180220_test_carto_zones_sensibles_nathan.zip](https://github.com/tomchadwin/qgis2web/files/1774309/180220_test_carto_zones_sensibles_nathan.zip)

I deposited my data and the result. It works only with integer fields (
or so I get a python message) but only consider year.

thanks for your help

**Comment by ruz76** [comment] 2018-03-02 18:28
I have tried OR_Historical_Counties from OR_AtlasHCB.zip and you are right, there is some problem with date to string conversion. I have added extra columns of text type based on START_DATE and END_DATE and extension works.

You can download the results from http://gisak.vsb.cz/ruzicka/down/time/OR_Atlas.zip

What I have to mention that I have used latest version of the extenstion from https://github.com/ruz76/qgis2web_time_extension. There can be some diffrences between merged version and the latest.

I will try to correct the bug.

**Comment by HerbFargus** [comment] 2018-03-02 18:54
Thanks! I'll give the data a test when I get a free moment later. 

Since the extension references are already in ui_maindialog.py, I imagine its just a simple swap of the ui_timedialog.py in the plugin directory?

**Comment by HerbFargus** [comment] 2018-03-03 02:52
@ruz76 Thanks, it looks good. 

I still think there may be nuances with QGIS 3 that may need to be ironed out (see also diffcheck above), I haven't tested on a 2.0 build to be able to reproduce the final htmls that you posted. I get this error in the stack trace:

https://pastebin.com/NJQa67Xq

and it doesn't show in the layers as an option:

![image](https://user-images.githubusercontent.com/10035308/36929774-ed0d0b90-1e52-11e8-974c-b6284293d7ad.png)

**Comment by ruz76** [comment] 2018-03-03 07:08
Yes. The QGIS 3 was not tested. There must be done some changes.

**Comment by ruz76** [comment] 2018-03-03 07:11
To @klrblz: 
I have tested the data from chonosignet and there is the same problem with date string conversion. I have added two extra fields in text format and it works. You can download result from https://github.com/ruz76/qgis2web_time_extension/blob/master/sample_output/chronogisnet.zip

What I have to mention that I have used latest version of the extenstion from https://github.com/ruz76/qgis2web_time_extension. There can be some diffrences between merged version and the latest.

I will try to correct the bug.

**Comment by ruz76** [comment] 2018-03-03 08:46
I have tried to fix the bug. The new version is available at https://github.com/ruz76/qgis2web_time_extension 

You just need to replace ui_timedialog.py with new one. 

It should work with date type field now. I have tested it only on chonosignet data fields DEBUT and FIN. I have tested only Open Layers export.

There must be done another tests, but I am quite bussy these days.

Migration to QGIS 3 is planned.

**Comment by klrblz** [comment] 2018-03-03 09:59
I just tried after downloading the latest version and it works perfectly with fields in text format.
Thank you very much for your advice and this great tool !
I'll let you know if I see other problems.

**Comment by noella08** [comment] 2018-03-19 12:56
I want to add a time slider to my qgis2web produced webmap. I am first trying it out using the chronogisnet data set. I have downloaded the "qgis2web_time_extension-master" and replaced the ui_timedialog.py file and also edited the ui_maindialog.py as it says to in the Readme . However, when i try to "add time" i get a python error 

**StopIteration** 
Traceback (most recent call last):
  File "C:/Users/Ikatutsi/.qgis2/python/plugins\qgis2web\ui_timedialog.py", line 296, in saveMap
    self.saveOLMap()
  File "C:/Users/Ikatutsi/.qgis2/python/plugins\qgis2web\ui_timedialog.py", line 431, in saveOLMap
    root, dirs, files = os.walk(dir).next()
StopIteration

Iam using qgis2.18.16 with 2.33.1qgis2web version.

**Closed** 2023-12-21 10:55 UTC
Labels: time
