### ISSUE TITLE
FILTERS in Qgis2Web 

### ISSUE THREAD

**Issue by JuaniMunozOv** [qgis2web/qgis2web#1052] opened 2024-03-07 01:50 UTC
Hello, it is a pleasure to communicate with you. 
I really wanted to know how to cover this problem because the code in html and css, as well as the layer filter.css is EXTENSIVELY long, in previous versions the filters were created within the layers and there were deployed and could be selected, now appear below or to the side of the map generated and really is not aesthetic, but I also want to know if I can add these filters or order them in a single button that does not appear the box with the attributes they have and their elements. I hope I understand, but now I attach an image of how they appear now and before it was inside the layers. 

![Qgis](https://github.com/qgis2web/qgis2web/assets/108429659/4796af99-fba4-400a-bf1a-45a02b8d4219)

**Comment by andreaordonselli** [comment] 2024-03-07 05:33
@riccardoklinger Can you provide an answer to this user?

I don't remember what the filter graphics looked like in previous versions, it seems to me that it has always been on the right as in your image.  In any case, would you like it if it were closed in an extensible button inside the map?

**Comment by riccardoklinger** [comment] 2024-03-07 05:54
Hi folks,

sorry for the hard language but "shitty data creates shitty filters". Make
sure to use long/integers/doubles for fields containing values. the filter
will then be a slider and not a dropdown. this might ease up the filter
veiw in the provided image.
Furthermore this is not a bug but a feature. If you create multiple filters
they will be listed as provided in the image. reduce the number of
filters...
It seems like you have an enhancement wish to make the filter section
somehow "minimizable" like with the layers box.
My knowledge in CSS is limited but this should be an easy task for a
developer.

Best Riccardo
______________________________________
"The best model for a cat is another, or preferably the same cat."

**Closed** 2024-03-11 18:02 UTC
