### ISSUE TITLE
Leaflet labels not showing for WFS layer

### ISSUE THREAD

**Issue by foundationkitty** [qgis2web/qgis2web#879] opened 2020-05-11 01:26 UTC
Hello, I am having an issue with WFS layers where labels are not shown with Leaflet. I tested with both QGIS 3.10.5 and 3.12.2, on the latter I also tested qgis2web 3.12.1, 3.8.0, and 3.3.0 in addition to 3.13.0. 

**What I got:**
![actresult](https://user-images.githubusercontent.com/45774850/81516121-b7fcf680-92eb-11ea-892a-f94e980817e6.PNG)
**What I have in QGIS canvas:**
![expected](https://user-images.githubusercontent.com/45774850/81516122-b8958d00-92eb-11ea-89cf-06640a6b1157.PNG)
**My settings:**
![settings](https://user-images.githubusercontent.com/45774850/81516069-9439b080-92eb-11ea-9fce-0b794a88a827.PNG)

**Comment by foundationkitty** [comment] 2020-05-13 00:17
I was able to reproduce this behavior with the following public URL:
http://geo.pacioos.hawaii.edu/geoserver/wfs?version=1.0.0&request=GetFeature?typeName%3DPACIOOS%3Agu_weri_sog_env_wlands

To clarify, OpenLayers shows the labels but leaflet doesn't.

**Comment by tomchadwin** [comment] 2020-05-13 10:16
I can see this issue, but at this stage, I honestly don't know what the problem is. Can anyone else figure it out? @riccardoklinger @walkermatt @webgeodatavore?

**Comment by RLH-GIS** [comment] 2020-08-18 16:40
Was there a fix for this yet? I am having the same issue with labels and WFS services

**Comment by ANDYAGUIRRE10** [comment] 2022-11-28 12:51
Hello! I am having a similar problem. I have created two labels with Inskcape, then and SLD in Qgis but when I upload this in Geoserver it doesn't take these labels.

**Closed** 2024-06-27 11:34 UTC
